// Auto-generated by SpritePack GUI v0.1
// Generated: 2026-01-06T08:12:33.926Z
export const SPRITEPACK_META = {
  "tool": "SpritePack_GUI",
  "version": "0.1.0",
  "generated_iso": "2026-01-06T08:12:33.926Z",
  "input": {
    "png": "jaloon.png",
    "json": "jaloon.json",
    "palette": "jaloon_palette.hex",
    "mode": "aseprite",
    "grid": null
  },
  "sprite_count": 14,
  "note": "Strict exact RGBA match. Alpha==0 treated as index0 (transparent)."
};

export const PALETTE_RGBA = [
  null, // 0: transparent
  [255,255,255,255],
  [255,17,0,255],
  [0,255,255,255],
  [255,255,0,255],
  [255,153,51,255],
  [51,153,0,255],
  [153,153,153,255],
];

export const SPRITES = {
  "jaloon (ply) 0": { w:16, h:16, packed4_b64:"AAAAAAAAAQAAAAAAAAABEAAAAAAAABEAAAAAAAAAEREQAAAAAAEQABEAAAABERERARAAARERAAAAAREQEREREAEQABEBEQAAEQABERAREQAQABEAEQEAABEREREREBAAAREREAERAAAAEREREQAAAAAAEREAAAAAAAAAAAAAAAA=" },
  "jaloon (ply) 1": { w:16, h:16, packed4_b64:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAARAAAAAAAAAAEQAAEREAAAAAEREBEREQABEAARARAAABEAAREBEREQEAARABARAAAREREREBEREQERERABARAAABERERABEREAABERAAERAAAAAAAAABEQAAAAAAAAEAA=" },
  "jaloon (enm) 0": { w:16, h:16, packed4_b64:"AAAAAAAAAAAAAAAAAAAAAAAAAAAiAAAAAAIAAiAAAAAAAiAiIAAAAAAAIiIiAAAAACIiICIiAAAAACAgICIiAAAAICAgIiIAACIiICIiAAAAACIiIgAAAAACICIgAAAAAAIAAiAAAAAAAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (enm) 1": { w:16, h:16, packed4_b64:"AAACAAAgAAAAAAIAACAAAAAAAiACIAAAAgACIAIgACACIAIgAiACIAAiAiACICIAACIiIAIiIgAAAiIiIiIgACACIiIiIiACIgAiAAAiACIiICIiIiICIgIiIAAAAiIgAiIiIiIiIiAAIgAAAAAiACIiIiIiIiIiAiIiAAAiIiA=" },
  "jaloon (arr) 0": { w:16, h:16, packed4_b64:"AAAAAAAAAAAAAAAAAAAAABEAAAEAAAAAEREREQAAAAAzMzMzAAAAADMAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (arr) 1": { w:16, h:16, packed4_b64:"ACIiAiAAAAAAAAIiIiAAAAIiACICIiAAIiAgAgICIiIiICACAgIiIgIiACICIiAAAAACIiIgAAAAIiICIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (blc) 0": { w:16, h:16, packed4_b64:"ARERAAAAAAAQAAEQAAAAABERERAAAAAAEAAREAAAAAAREREQAAAAABABERAAAAAAARERAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (blc) 1": { w:16, h:16, packed4_b64:"ACACAAAAAAAAIiIAAAAAACIgAiIAAAAAAiIiIAAAAAACIiIgAAAAACIgAiIAAAAAACIiAAAAAAAAIAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (dft) 0": { w:16, h:16, packed4_b64:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHcAAAAAAAAHcAAAAAB3AHdwdwAAAAdwdwd3cAAAAAcHd3cAAAAAdwdwdwAAAAB3BwdwAAAAAAd3cAAAAAAAdwd3cAAAAAdwAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (dft) 1": { w:16, h:16, packed4_b64:"AAAABwAAAAAAd3B3d3AAAAAHd3B3d3AAAHcHdwcHd3AHcHcHB3cAAAdwdwdwAAAAAHcHdwAAAAAAAHcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (itm) 0": { w:16, h:16, packed4_b64:"AAAAAAAAAAAiAAAAAAAAACIgAAAAAAAAIiIAAAAAAAAiIgAAAAAAACIgAAAAAAAAIgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (itm) 1": { w:16, h:16, packed4_b64:"AAQAAAAAAAAEBAQAAAAAAABEQAAAAAAAREREQAAAAAAAREAAAAAAAAQEBAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" },
  "jaloon (grn) 0": { w:16, h:16, packed4_b64:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAZgAAAGAAAAZmYAAGZgBgBmZmAGZmAGYGZmYGZmYGZmZmZmZmZmZmZmZmY=" },
  "jaloon (grn) 1": { w:16, h:16, packed4_b64:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAZmAAAAAAAAZmYAAGBgAABmZmAGYGZgBmZmYGZgZmYGZmZmZmZmZmZmZmZmY=" },
};

// --- runtime helpers (optional) ---
export function spritepackBuildCanvases() {
  const canvases = {};
  for (const [key, sp] of Object.entries(SPRITES)) {
    canvases[key] = spritepackBuildCanvas(sp);
  }
  return canvases;
}

export function spritepackBuildCanvas(sp) {
  const { w, h, packed4_b64 } = sp;
  const packed = spritepackB64ToU8(packed4_b64);
  const idx = spritepackUnpack4(packed, w * h);
  const c = document.createElement("canvas");
  c.width = w; c.height = h;
  const ctx = c.getContext("2d");
  const img = ctx.createImageData(w, h);
  const d = img.data;
  for (let i = 0; i < idx.length; i++) {
    const pi = i * 4;
    const p = PALETTE_RGBA[idx[i]];
    if (!p) { d[pi]=0; d[pi+1]=0; d[pi+2]=0; d[pi+3]=0; continue; }
    d[pi] = p[0]; d[pi+1] = p[1]; d[pi+2] = p[2]; d[pi+3] = p[3];
  }
  ctx.putImageData(img, 0, 0);
  return c;
}

export function spritepackB64ToU8(b64) {
  const bin = atob(b64);
  const u8 = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);
  return u8;
}

export function spritepackUnpack4(packedBytes, pixelCount) {
  const out = new Uint8Array(pixelCount);
  let oi = 0;
  for (let i = 0; i < packedBytes.length; i++) {
    const b = packedBytes[i];
    out[oi++] = (b >> 4) & 0x0f;
    if (oi < pixelCount) out[oi++] = b & 0x0f;
  }
  return out;
}
